"""
round 3: some of the turns are misaligned or incomplete, we could do dialogue-level reconstruction to fix the flow and fill in missing turns, but still keep the same emotional texture and spoken language style.
"""
import json
import os
import sys
from pathlib import Path

from openai import OpenAI

BASE_DIR = Path(__file__).resolve().parent

# Simple .env loader (no extra dependency)
env_path = BASE_DIR / ".env"
if env_path.exists():
    with open(env_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                os.environ.setdefault(key.strip(), value.strip())
DATA_FILE = BASE_DIR / "output_logic.py"
OUTPUT_FILE = BASE_DIR / "output_complete.py"

PROMPT = """
You are reconstructing corrupted Chinese debt-collection phone call transcripts generated by ASR.

This is NOT sentence-level proofreading.

This is:

dialogue-level conversational reconstruction

The transcript may contain:

* ASR corruption
* missing utterances
* broken turn segmentation
* misplaced turns
* fragmented clauses
* duplicated fragments
* incomplete responses
* missing acknowledgements
* interrupted semantic flow
* incorrectly split dialogue turns
* merged turns that should be separated

Your task is NOT to preserve every original utterance.

Your real goal is:

reconstruct the most likely natural conversation

The final dialogue should:

* flow logically
* sound naturally spoken
* preserve emotional realism
* preserve negotiation dynamics
* preserve spoken Mandarin rhythm
* preserve debt-collection conversational style

VERY IMPORTANT:
Optimize for:

1. conversational coherence
2. semantic continuity
3. realistic dialogue rhythm
4. emotional flow

NOT:

* literal ASR preservation
* token-level fidelity
* sentence-by-sentence repair

⸻

CORE RECONSTRUCTION RULES

You MAY:

* merge fragmented turns
* split wrongly merged turns
* reorder clearly misplaced turns
* rewrite corrupted ASR spans semantically
* infer omitted conversational transitions
* insert missing short replies
* insert acknowledgement turns
* reconstruct implied responses
* remove duplicated garbage fragments
* normalize impossible wording

You SHOULD:

* reduce unnatural runs of consecutive 催收员 turns
* restore natural back-and-forth rhythm
* infer customer reactions when clearly implied
* reconstruct hidden adjacency pairs
* connect broken semantic chains

You MUST preserve:

* original intent
* repayment negotiation logic
* emotional pressure
* hesitation
* spoken-language style
* colloquial customer-service tone

⸻

IMPORTANT SPEECH STYLE RULES

Keep spoken conversational texture:

* “嗯”
* “呃”
* “就是说”
* “嘛”
* “这个”
* hesitation
* pauses
* partial repetition
* emotional stalling

DO NOT rewrite into formal written Chinese.

GOOD:
“嗯，先生，这边的话目前确实没有这个方案。”

BAD:
“目前我行暂未提供该项服务方案。”

⸻

VERY IMPORTANT:
DIALOGUE RHYTHM RECONSTRUCTION

ASR transcripts often lose short customer responses.

If a long 催收员 monologue contains:

* topic shifts
* rhetorical questions
* emotional responses
* implied interruptions
* references to something the customer supposedly said

then you SHOULD infer and insert short missing customer turns.

Examples:

* “嗯”
* “对”
* “那怎么办”
* “我现在确实困难”
* “能不能重新分期”
* “一次性我拿不出来”
* “利息太高了”

These inferred turns should:

* be short
* sound natural
* fit emotional context
* preserve negotiation realism

⸻

AI GENERATED TURN RULE

If you generate or reconstruct a missing turn:

add:
“label”: “1”

Example:
{
“role”: “客户”,
“text”: “一次性我肯定拿不出来啊。”,
“label”: “1”
}

Do NOT label original turns.

⸻

TURN RECONSTRUCTION RULES

If consecutive turns from the same speaker are clearly fragments of one utterance:

* merge them

If one turn contains multiple distinct intents:

* split them

If a turn is semantically incomplete:

* reconstruct it using nearby context

If a phrase is obvious ASR garbage:

* replace it with the most likely spoken utterance

Examples:

BAD INPUT:
“后面话。好的就是说”

GOOD:
“好的，就是说”

BAD INPUT:
“20000万6000嗯，462块6毛一”

GOOD:
“26462块6毛1”

BAD INPUT:
“能够办理”

GOOD:
(remove or merge into neighboring turn)

⸻

CONVERSATIONAL COHERENCE OVERRIDES LITERAL FIDELITY

If preserving the literal ASR output harms:

* readability
* dialogue realism
* emotional continuity
* negotiation flow

then reconstruct the dialogue naturally instead.

Prefer:

* natural conversational structure
    over:
* literal corrupted wording

⸻

OUTPUT REQUIREMENTS

* Output valid JSON only
* Preserve overall structure
* Preserve role fields
* Preserve chronological flow
* Keep spoken Mandarin style
* Do not explain edits
* Do not summarize

Transcript:
"""


def create_client() -> OpenAI:
    api_key = os.environ.get("DEEPSEEK_API_KEY")
    if not api_key:
        print("Error: DEEPSEEK_API_KEY environment variable is not set.")
        sys.exit(1)
    return OpenAI(api_key=api_key, base_url="https://api.deepseek.com")


def load_all_records() -> list[dict]:
    # output_2.py defines a top-level `results` list
    with open(DATA_FILE, "r", encoding="utf-8") as f:
        code = compile(f.read(), DATA_FILE, "exec")
        namespace = {}
        exec(code, namespace)
        data = namespace.get("results", [])

    records = []
    for item in data:
        record = item.get("record", item)
        records.append(record)

    print(f"Loaded {len(records)} records")
    return records


def call_llm(client: OpenAI, system_prompt: str, user_data: dict,
             max_tokens: int = 16384) -> dict:
    user_message = json.dumps(user_data, ensure_ascii=False)
    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {"role": "system", "content": system_prompt.strip()},
            {"role": "user", "content": user_message},
        ],
        temperature=0.1,
        max_tokens=max_tokens,
        response_format={"type": "json_object"},
    )
    content = response.choices[0].message.content
    if response.choices[0].finish_reason == "length":
        print("  Warning: response truncated")
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        pass

    print("  Attempting to fix truncated JSON...")
    if content.rstrip().endswith("}"):
        pass
    else:
        depth = 0
        in_str = False
        escape = False
        for i, ch in enumerate(content):
            if escape:
                escape = False
                continue
            if ch == '\\':
                escape = True
                continue
            if ch == '"' and not escape:
                in_str = not in_str
                continue
            if in_str:
                continue
            if ch in '{[':
                depth += 1
            elif ch in '}]':
                depth -= 1

        if in_str:
            content = content + '"'
        while depth > 0:
            content = content + '}'
            depth -= 1

    try:
        return json.loads(content)
    except json.JSONDecodeError as e:
        print(f"  JSON repair failed: {e}")
        raise


def main() -> None:
    client = create_client()
    records = load_all_records()

    results = []
    for i, record in enumerate(records):
        print(f"  Processing record {i+1}/{len(records)} (call_id={record['call_id']})...")
        result = call_llm(client, PROMPT, {"record": record})
        results.append(result)

    with open(OUTPUT_FILE, "w+", encoding="utf-8") as f:
        f.write("results = ")
        f.write(json.dumps(results, ensure_ascii=False, indent=2))
        f.write("\n")

    print(f"Output written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
