[mypy]
warn_unused_ignores = true
ignore_missing_imports = true
exclude = (build_tree_and_db|whole_pipeline|launch_ui|check_data_format|serve_tree|data/)

[mypy-f005_context_scoring.*]
ignore_errors = true

[mypy-f004_decision_tree.*]
ignore_errors = true

[mypy-f003_reward_labeling.*]
ignore_errors = true

[mypy-f001_schema_alignment.*]
ignore_errors = true

[mypy-f000_keyword_discovery.*]
ignore_errors = true

[mypy-f010_api_mock_ui.*]
ignore_errors = true
