"""
round 3: some of the turns are misaligned or incomplete, we could do dialogue-level reconstruction to fix the flow and fill in missing turns, but still keep the same emotional texture and spoken language style.
"""
import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI

from f007_infrastructure.config import get as _cfg
from f007_infrastructure.jsonl_utils import load_jsonl, write_jsonl
from f007_infrastructure.llm_client import _get_client
from f007_infrastructure.retry import retry_call

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
INPUT_DIR = _PROJECT_ROOT / "data" / "data_input"
OUTPUT_DIR = _PROJECT_ROOT / "data" / "data_output"
load_dotenv(_PROJECT_ROOT / ".env")
DATA_FILE = Path(os.environ.get("DATA_FILE", str(OUTPUT_DIR / "output_logic.jsonl")))
OUTPUT_FILE = Path(os.environ.get("OUTPUT_FILE", str(OUTPUT_DIR / "output_complete.jsonl")))

PROMPT = """
You are reconstructing corrupted Chinese debt-collection phone call transcripts generated by ASR.

This is NOT sentence-level proofreading.

This is:

dialogue-level conversational reconstruction

The transcript may contain:

* ASR corruption
* missing utterances
* broken turn segmentation
* misplaced turns
* fragmented clauses
* duplicated fragments
* incomplete responses
* missing acknowledgements
* interrupted semantic flow
* incorrectly split dialogue turns
* merged turns that should be separated

Your task is NOT to preserve every original utterance.

Your real goal is:

reconstruct the most likely natural conversation

The final dialogue should:

* flow logically
* sound naturally spoken
* preserve emotional realism
* preserve negotiation dynamics
* preserve spoken Mandarin rhythm
* preserve debt-collection conversational style

VERY IMPORTANT:
Optimize for:

1. conversational coherence
2. semantic continuity
3. realistic dialogue rhythm
4. emotional flow

NOT:

* literal ASR preservation
* token-level fidelity
* sentence-by-sentence repair

⸻

CORE RECONSTRUCTION RULES

You MAY:

* merge fragmented turns
* split wrongly merged turns
* reorder clearly misplaced turns
* rewrite corrupted ASR spans semantically
* infer omitted conversational transitions
* insert missing short replies
* insert acknowledgement turns
* reconstruct implied responses
* remove duplicated garbage fragments
* normalize impossible wording

You SHOULD:

* reduce unnatural runs of consecutive 催收员 turns
* restore natural back-and-forth rhythm
* infer customer reactions when clearly implied
* reconstruct hidden adjacency pairs
* connect broken semantic chains

You MUST preserve:

* original intent
* repayment negotiation logic
* emotional pressure
* hesitation
* spoken-language style
* colloquial customer-service tone

⸻

IMPORTANT SPEECH STYLE RULES

Keep spoken conversational texture:

* “嗯”
* “呃”
* “就是说”
* “嘛”
* “这个”
* hesitation
* pauses
* partial repetition
* emotional stalling

DO NOT rewrite into formal written Chinese.

GOOD:
“嗯，先生，这边的话目前确实没有这个方案。”

BAD:
“目前我行暂未提供该项服务方案。”

⸻

VERY IMPORTANT:
DIALOGUE RHYTHM RECONSTRUCTION

ASR transcripts often lose short customer responses.

If a long 催收员 monologue contains:

* topic shifts
* rhetorical questions
* emotional responses
* implied interruptions
* references to something the customer supposedly said

then you SHOULD infer and insert short missing customer turns.

Examples:

* “嗯”
* “对”
* “那怎么办”
* “我现在确实困难”
* “能不能重新分期”
* “一次性我拿不出来”
* “利息太高了”

These inferred turns should:

* be short
* sound natural
* fit emotional context
* preserve negotiation realism

⸻

AI GENERATED TURN RULE

If you generate or reconstruct a missing turn:

add:
“label”: “1”

Example:
{
“role”: “客户”,
“text”: “一次性我肯定拿不出来啊。”,
“label”: “1”
}

Do NOT label original turns.

⸻

TURN RECONSTRUCTION RULES

If consecutive turns from the same speaker are clearly fragments of one utterance:

* merge them

If one turn contains multiple distinct intents:

* split them

If a turn is semantically incomplete:

* reconstruct it using nearby context

If a phrase is obvious ASR garbage:

* replace it with the most likely spoken utterance

Examples:

BAD INPUT:
“后面话。好的就是说”

GOOD:
“好的，就是说”

BAD INPUT:
“20000万6000嗯，462块6毛一”

GOOD:
“26462块6毛1”

BAD INPUT:
“能够办理”

GOOD:
(remove or merge into neighboring turn)

⸻

CONVERSATIONAL COHERENCE OVERRIDES LITERAL FIDELITY

If preserving the literal ASR output harms:

* readability
* dialogue realism
* emotional continuity
* negotiation flow

then reconstruct the dialogue naturally instead.

Prefer:

* natural conversational structure
    over:
* literal corrupted wording

⸻

OUTPUT REQUIREMENTS

* Output valid JSON only
* Preserve overall structure
* Preserve role fields
* Preserve chronological flow
* Keep spoken Mandarin style
* Do not explain edits
* Do not summarize

Output valid JSON only.
{"dialog": [
    {
      "role": "催收员",
      "text": "唉，您好，请问是……喂，您好，请问是。"
    },
    {
      "role": "客户",
      "text": "喂。"
    },
    {
      "role": "客户",
      "text": "一次性我肯定拿不出来啊。",
      "label": "1"
    }
]}

Transcript:
"""


def create_client() -> OpenAI:
    return _get_client()


def load_all_records() -> list[dict]:
    data = load_jsonl(DATA_FILE)

    records = []
    for item in data:
        entry = {
            "call_id": item.get("call_id", ""),
            "dialog": item.get("response", item),
        }
        if "custInfo" in item:
            entry["custInfo"] = item["custInfo"]
        records.append(entry)

    print(f"Loaded {len(records)} records")
    return records


def repair_json(content: str) -> str:
    import re as _re
    last_complete = _re.rfind(content, '},')
    if last_complete != -1:
        truncated = content[:last_complete + 1]
        if '"dialog"' in truncated:
            depth = 0
            in_str = False
            escape = False
            for ch in truncated:
                if escape:
                    escape = False
                    continue
                if ch == '\\':
                    escape = True
                    continue
                if ch == '"' and not escape:
                    in_str = not in_str
                    continue
                if in_str:
                    continue
                if ch in '{[':
                    depth += 1
                elif ch in '}]':
                    depth -= 1
            if in_str:
                truncated += '"'
            while depth > 0:
                truncated += ']}' if depth >= 2 else '}'
                depth -= 2 if depth >= 2 else 1
            return truncated
    depth = 0
    in_str = False
    escape = False
    for ch in content:
        if escape:
            escape = False
            continue
        if ch == '\\':
            escape = True
            continue
        if ch == '"' and not escape:
            in_str = not in_str
            continue
        if in_str:
            continue
        if ch in '{[':
            depth += 1
        elif ch in '}]':
            depth -= 1
    if in_str:
        content += '"'
    while depth > 0:
        content += '}'
        depth -= 1
    return content


def call_llm(client: OpenAI, system_prompt: str, dialog: list[dict],
             max_tokens: int = _cfg("llm.max_tokens", 16384)) -> dict:
    user_message = json.dumps(dialog, ensure_ascii=False)
    response = client.chat.completions.create(
        model=_cfg("llm.model", "deepseek-chat"),
        messages=[
            {"role": "system", "content": system_prompt.strip()},
            {"role": "user", "content": user_message},
        ],
        temperature=_cfg("llm.temperature", 0.1),
        max_tokens=max_tokens,
        response_format={"type": "json_object"},
    )
    content = response.choices[0].message.content
    if response.choices[0].finish_reason == "length":
        print("  Warning: response truncated")
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        pass

    print("  Attempting to fix truncated JSON...")
    repaired = repair_json(content)
    try:
        return json.loads(repaired)
    except json.JSONDecodeError as e:
        print(f"  JSON repair failed: {e}")
        raise


def load_existing_results() -> list[dict]:
    if not OUTPUT_FILE.exists():
        return []
    return load_jsonl(OUTPUT_FILE)


def write_results(results: list[dict]) -> None:
    write_jsonl(OUTPUT_FILE, results)


def main() -> None:
    client = create_client()
    records = load_all_records()
    results = load_existing_results()
    existing_call_ids = {r["call_id"] for r in results}

    BATCH_SIZE = _cfg("batch_size.data_cleaning", 1)
    batch = []

    for i, record in enumerate(records):
        if record["call_id"] in existing_call_ids:
            print(f"  Skipping record {i+1}/{len(records)} (call_id={record['call_id']}) - already processed")
            continue
        print(f"  Processing record {i+1}/{len(records)} (call_id={record['call_id']})...")
        def _process():
            llm_response = call_llm(client, PROMPT, record["dialog"])
            out = {
                "call_id": record["call_id"],
                "response": llm_response,
            }
            if "custInfo" in record:
                out["custInfo"] = record["custInfo"]
            return out

        def _on_fail(exc):
            print(f"  SKIPPED record {i+1}/{len(records)} (call_id={record['call_id']}) after 3 retries: {exc}")
            return None

        result = retry_call(_process, on_fail=_on_fail)
        if result is None:
            continue
        results.append(result)
        batch.append(result)

        if len(batch) >= BATCH_SIZE:
            write_results(results)
            print(f"  Checkpoint: {len(results)} results written to {OUTPUT_FILE}")
            batch.clear()

    if batch:
        write_results(results)
        print(f"  Final: {len(results)} results written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
