REQUIRED_FIELDS = ["id", "title", "doc_kind", "created", "schema_version"]
DOC_KIND_ENUM = ["decision", "lesson", "spec", "plan", "discussion", "research", "bug-report", "review", "note", "summary"]
STATUS_ENUM = ["draft", "review", "accepted", "deprecated", "superseded", "archived"]
AUTHORITY_ENUM = ["observed", "candidate", "validated", "constitutional"]
ACTIVATION_ENUM = ["query", "scoped", "always_on", "backstop"]
KNOWLEDGE_STATUS_ENUM = ["active", "review", "invalidated", "archived"]
EXPORTABILITY_ENUM = ["private", "project_only", "generalized"]
ARTIFACT_TYPE_ENUM = ["episode", "method", "skill", "proposal", "eval", "lesson", "log"]
DOMAIN_ENUM = ["development", "ops", "product", "design", "general"]
SCOPE_ENUM = ["agent-local", "team-shared"]
LESSON_ID_PATTERN = r"^LL-\d{3}$"
ADR_ID_PATTERN = r"^ADR-\d{3}$"
